name: README_RSS_FEED_CI

on:
  workflow_dispatch:
    inputs:
      description:
        description: 'What updated on my blog'
        required: false

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: qiita
        uses: sarisia/actions-readme-feed@v1.2.0
        id: qiita_feed
        with:
          url: 'https://qiita.com/huuya/feed'
          file: 'README.md'
          start_flag: "<!-- qiita start -->"
          end_flag: "<!-- qiita end -->"
      - name: blog
        uses: sarisia/actions-readme-feed@v1.2.0
        id: blog_feed
        with:
          url: 'https://huuya.ga/rss.xml'
          file: 'README.md'
          start_flag: "<!-- blog start -->"
          end_flag: "<!-- blog end -->"
      - name: zenn
        uses: sarisia/actions-readme-feed@v1.2.0
        id: zenn_feed
        with:
          url: 'https://zenn.dev/huuya/feed'
          file: 'README.md'
          start_flag: "<!--zenn start -->"
          end_flag: "<!-- zenn end -->"
      - if: ${{ steps.qiita_feed.outputs.changed == true || steps.blog_feed.outputs.changed == true || steps.zenn_feed.outputs.changed == true}}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin master
          git add .
          git commit -m "docs: update feed" || true
          git push
